FROM nginx:1.25-alpine

# Set Timezone
ENV TZ=Asia/Jakarta
RUN apk add --no-cache tzdata

# Remove default nginx static assets
RUN rm -rf /usr/share/nginx/html/*

# Copy Custom Nginx Configuration
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Copy Pre-compiled Flutter Web Release Assets
COPY build/web /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
